Finished Arch and Fedora Sections
Open-Source-Community/LDP-2024 pull request #9
Opened 2024-03-06 14:19 UTC by thisisamna

Finished Arch and Fedora sections for LDP 2024, closes #1 , closes #5

2024-03-06 15:15 UTC, Dimitry-bit requested changes
Both reviews are quite rough and require more polish. Please fix the following issues and re-request a review.

2024-03-06 15:15 UTC, Dimitry-bit commented on Arch/README.md
> +![](imgs/secondpage.img.png)
The installation guide is uninformative and provides no real value to the user; it is better to just remove it.

2024-03-06 15:15 UTC, Dimitry-bit commented on Fedora/README.md
> +![Fedora_LOGO](Imgs/Fedora_LOGO.png)
The logo is huge. Set it to a reasonable size.

2024-03-06 15:15 UTC, Dimitry-bit commented on Fedora/README.md
> +
The screenshots clearly display Windows' taskbar, which is unacceptable.

2024-03-06 15:15 UTC, Dimitry-bit commented on Fedora/README.md
> +1. Enjoy using Fedora!
This installation guide is labeled for dual boot but fails to mention any dual boot related information throughout the guide. 

2024-03-06 17:14 UTC, thisisamna commented on Fedora/README.md
> +1. Enjoy using Fedora!
On it! Appreciate the feedback

2024-03-09 18:52 UTC, Dimitry-bit requested changes
Great work, but some duplication exists.

2024-03-09 18:52 UTC, Dimitry-bit commented on Fedora/README.md
> +
Fix duplication.

2024-03-09 18:52 UTC, Dimitry-bit commented on Fedora/README.md
> +
More duplication.

2024-03-11 19:45 UTC, Dimitry-bit approved these changes
Nice work!

2024-03-11 19:45 UTC, merged

2024-03-11 19:47 UTC, thisisamna commented
Appreciate the reviews and feedback!